console.log "== Equal: #{1==1}"
console.log "!= Not equal: #{1!=2}"
console.log "> Greather than: #{2>1}"
console.log ">= Greather than or equal: #{1>=1}"
console.log "< Less than: #{1<2}"
console.log "<= Less than or equal: #{1<=2}"
console.log "=== Identical: #{'a' === 'a'}"
console.log "!== Not identical: #{1 !== 2}"
